# Generated by Django 3.2.18 on 2023-03-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0004_rename_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blabhear.message'),
        ),
    ]
