# Generated by Django 3.2.18 on 2023-03-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0006_messagenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagenotification',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blabhear.message'),
            preserve_default=False,
        ),
    ]
